### ISSUE TITLE
Admin section preview crashes web browser.

### ISSUE THREAD

**Issue by Septimus** [Musare/MusareMeteor#34] opened 2015-11-27 16:32 UTC
Tested with Firefox.
Number of tries: 5

When trying to preview a song inside of the admin section and hit play Firefox crashes. Not a super important issue as it isn't user facing but I will look into it if nobody else does quickly.

**Comment by KrisVos130** [comment] 2015-11-27 16:57
Can't reproduce on the Firefox Developer edition.

**Comment by Septimus** [comment] 2015-11-28 19:14
Huh. Maybe it is Firefox Mac specific? I'll continue to do some research.

**Comment by KrisVos130** [comment] 2015-11-28 20:08
Fixed in 73ce783.

**Closed as completed by KrisVos130** 2015-11-28 20:08 UTC
Labels: bug
